const model = {
    sort: {
        field: 'meal',
        direction: null,
    },
    costStats: [
        {
            rank: 1,
            country: "Switzerland",
            meal: 1317.66,
            beer: 83.85,
            wine: 149.73,
            apartment: 19879.32,
            coffee: 58.07
        },
        {
            rank: 2,
            country: "Denmark",
            meal: 1077.83,
            beer: 76.99,
            wine: 100.08,
            apartment: 11849.16,
            coffee: 60.18
        },
        {
            rank: 3,
            country: "Norway",
            meal: 1000,
            beer: 98.5,
            wine: 150,
            apartment: 11305.64,
            coffee: 45.46
        },
        {
            rank: 4,
            country: "Finland",
            meal: 918.96,
            beer: 80.41,
            wine: 137.84,
            apartment: 9054.19,
            coffee: 45.19
        },
        {
            rank: 5,
            country: "Ireland",
            meal: 918.96,
            beer: 63.18,
            wine: 126.36,
            apartment: 16948.07,
            coffee: 40.49
        },
        {
            rank: 6,
            country: "Belgium",
            meal: 861.52,
            beer: 45.95,
            wine: 80.41,
            apartment: 9373.92,
            coffee: 36.73
        },
        {
            rank: 7,
            country: "Israel",
            meal: 838.35,
            beer: 83.84,
            wine: 111.78,
            apartment: 11163.06,
            coffee: 38.19
        },
        {
            rank: 8,
            country: "Luxembourg",
            meal: 829.36,
            beer: 57.43,
            wine: 91.9,
            apartment: 18048.25,
            coffee: 42.42
        },
        {
            rank: 9,
            country: "Australia",
            meal: 825.85,
            beer: 68.82,
            wine: 137.64,
            apartment: 16015.78,
            coffee: 36.06
        },
        {
            rank: 10,
            country: "Malta",
            meal: 804.09,
            beer: 34.46,
            wine: 68.92,
            apartment: 10218.66,
            coffee: 27.34
        },
        {
            rank: 11,
            country: "Netherlands",
            meal: 804.09,
            beer: 57.43,
            wine: 68.81,
            apartment: 13791.96,
            coffee: 35.88
        },
        {
            rank: 12,
            country: "United Kingdom",
            meal: 801.71,
            beer: 60.13,
            wine: 93.53,
            apartment: 12426.08,
            coffee: 40.53
        },
        {
            rank: 13,
            country: "United States",
            meal: 801.62,
            beer: 64.13,
            wine: 149.58,
            apartment: 19636.06,
            coffee: 51.48
        },
        {
            rank: 14,
            country: "Singapore",
            meal: 786.27,
            beer: 78.63,
            wine: 235.88,
            apartment: 35226.1,
            coffee: 48.37
        },
        {
            rank: 15,
            country: "Sweden",
            meal: 769.54,
            beer: 69.26,
            wine: 96.19,
            apartment: 8774.71,
            coffee: 39.97
        },
        {
            rank: 16,
            country: "New Zealand",
            meal: 760.47,
            beer: 63.37,
            wine: 101.4,
            apartment: 11734.95,
            coffee: 34.5
        },
        {
            rank: 17,
            country: "Puerto Rico",
            meal: 748.18,
            beer: 25.38,
            wine: 160.32,
            apartment: 12076.41,
            coffee: 33
        },
        {
            rank: 18,
            country: "Canada",
            meal: 710.77,
            beer: 55.28,
            wine: 134.26,
            apartment: 13365.69,
            coffee: 38.11
        },
        {
            rank: 19,
            country: "Germany",
            meal: 689.22,
            beer: 45.95,
            wine: 57.43,
            apartment: 9609.97,
            coffee: 36.83
        },
        {
            rank: 20,
            country: "Cyprus",
            meal: 689.22,
            beer: 34.46,
            wine: 80.41,
            apartment: 11163.77,
            coffee: 37.62
        },
        {
            rank: 21,
            country: "Austria",
            meal: 689.22,
            beer: 45.95,
            wine: 80.41,
            apartment: 9431.83,
            coffee: 39.27
        },
        {
            rank: 22,
            country: "Italy",
            meal: 689.22,
            beer: 57.43,
            wine: 68.92,
            apartment: 7667.68,
            coffee: 17.67
        },
        {
            rank: 23,
            country: "France",
            meal: 689.22,
            beer: 68.92,
            wine: 80.41,
            apartment: 8291.38,
            coffee: 33.38
        },
        {
            rank: 24,
            country: "Hong Kong (China)",
            meal: 682.83,
            beer: 68.28,
            wine: 204.85,
            apartment: 24907.14,
            coffee: 54.69
        },
        {
            rank: 25,
            country: "Estonia",
            meal: 654.76,
            beer: 51.69,
            wine: 91.9,
            apartment: 6459.92,
            coffee: 35.22
        },
        {
            rank: 26,
            country: "Costa Rica",
            meal: 599.57,
            beer: 29.98,
            wine: 139.9,
            apartment: 6417.64,
            coffee: 33.74
        },
        {
            rank: 27,
            country: "Panama",
            meal: 587.86,
            beer: 21.38,
            wine: 96.19,
            apartment: 8770.94,
            coffee: 37.01
        },
        {
            rank: 28,
            country: "Qatar",
            meal: 587.11,
            beer: "-",
            wine: "-",
            apartment: 17713.21,
            coffee: 57.91
        },
        {
            rank: 29,
            country: "United Arab Emirates",
            meal: 581.99,
            beer: 113.49,
            wine: 145.5,
            apartment: 12995.06,
            coffee: 54.12
        },
        {
            rank: 30,
            country: "Latvia",
            meal: 574.35,
            beer: 39.06,
            wine: 80.41,
            apartment: 4316.62,
            coffee: 28.72
        },
        {
            rank: 31,
            country: "Lithuania",
            meal: 574.35,
            beer: 49.39,
            wine: 91.78,
            apartment: 7113.41,
            coffee: 32.93
        },
        {
            rank: 32,
            country: "Uruguay",
            meal: 558.69,
            beer: 41.9,
            wine: 83.8,
            apartment: 6429.62,
            coffee: 44.41
        },
        {
            rank: 33,
            country: "Armenia",
            meal: 554.99,
            beer: "18.apr",
            wine: 97.12,
            apartment: 10665,
            coffee: 33.38
        },
        {
            rank: 34,
            country: "Kuwait",
            meal: 554.22,
            beer: "-",
            wine: "-",
            apartment: 9326.15,
            coffee: 54.98
        },
        {
            rank: 35,
            country: "Jamaica",
            meal: 553.71,
            beer: 24.22,
            wine: 103.82,
            apartment: 4925.51,
            coffee: 34.2
        },
        {
            rank: 36,
            country: "Venezuela",
            meal: 534.42,
            beer: "16.mar",
            wine: 85.51,
            apartment: 2178.21,
            coffee: 19.94
        },
        {
            rank: 37,
            country: "Croatia",
            meal: 534.14,
            beer: 30.44,
            wine: 61.23,
            apartment: 5554.38,
            coffee: 20.78
        },
        {
            rank: 38,
            country: "Greece",
            meal: 516.91,
            beer: 45.95,
            wine: 80.41,
            apartment: 4760.42,
            coffee: 36.49
        },
        {
            rank: 39,
            country: "Spain",
            meal: 516.91,
            beer: 28.72,
            wine: 57.43,
            apartment: 8697.42,
            coffee: 20.26
        },
        {
            rank: 40,
            country: "Slovenia",
            meal: 516.91,
            beer: 32.16,
            wine: 68.92,
            apartment: 6887.44,
            coffee: 20.35
        },
        {
            rank: 41,
            country: "Saudi Arabia",
            meal: 484.42,
            beer: "-",
            wine: "-",
            apartment: 5009.43,
            coffee: 40.47
        },
        {
            rank: 42,
            country: "Chile",
            meal: 481.9,
            beer: 36.14,
            wine: 54.21,
            apartment: 4909.37,
            coffee: "30.sep"
        },
        {
            rank: 43,
            country: "Dominican Republic",
            meal: 470.79,
            beer: 28.25,
            wine: 103.57,
            apartment: 5132.79,
            coffee: 22.45
        },
        {
            rank: 44,
            country: "Portugal",
            meal: 459.48,
            beer: 22.97,
            wine: 45.95,
            apartment: 9077.09,
            coffee: 16.7
        },
        {
            rank: 45,
            country: "Jordan",
            meal: 452.77,
            beer: 67.92,
            wine: 226.38,
            apartment: 3349.36,
            coffee: 37.25
        },
        {
            rank: 46,
            country: "Hungary",
            meal: 449.06,
            beer: 20.96,
            wine: 47.9,
            apartment: 5009.73,
            coffee: 20.42
        },
        {
            rank: 47,
            country: "Belarus",
            meal: 423.56,
            beer: 13.9,
            wine: 84.71,
            apartment: 3830.64,
            coffee: 19.67
        },
        {
            rank: 48,
            country: "Bulgaria",
            meal: 410.98,
            beer: 20.55,
            wine: 58.71,
            apartment: 4001.9,
            coffee: 19.76
        },
        {
            rank: 49,
            country: "Georgia",
            meal: 407.95,
            beer: 18.36,
            wine: 65.27,
            apartment: 7932.54,
            coffee: 29.86
        },
        {
            rank: 50,
            country: "South Korea",
            meal: 403.47,
            beer: 32.28,
            wine: 161.39,
            apartment: 5369.31,
            coffee: 39.13
        },
        {
            rank: 51,
            country: "Slovakia",
            meal: 402.04,
            beer: 20.68,
            wine: 57.43,
            apartment: 6028.52,
            coffee: 23.81
        },
        {
            rank: 52,
            country: "Montenegro",
            meal: 402.04,
            beer: 25.27,
            wine: 57.43,
            apartment: 6181.3,
            coffee: 19.98
        },
        {
            rank: 53,
            country: "Poland",
            meal: 397.32,
            beer: 29.8,
            wine: 62.08,
            apartment: 7232.2,
            coffee: 30.89
        },
        {
            rank: 54,
            country: "Czech Republic",
            meal: 386.12,
            beer: 21.16,
            wine: 61.14,
            apartment: 7754.9,
            coffee: 28.67
        },
        {
            rank: 55,
            country: "Romania",
            meal: 383.53,
            beer: 18.49,
            wine: 57.79,
            apartment: 4082.29,
            coffee: 23.56
        },
        {
            rank: 56,
            country: "Albania",
            meal: 377.62,
            beer: 21.58,
            wine: 86.31,
            apartment: 4028.73,
            coffee: 15.76
        },
        {
            rank: 57,
            country: "Mexico",
            meal: 374.59,
            beer: 24.97,
            wine: 124.86,
            apartment: 5916.51,
            coffee: 32.12
        },
        {
            rank: 58,
            country: "Ecuador",
            meal: 374.09,
            beer: 21.38,
            wine: 105.81,
            apartment: 3965.78,
            coffee: 25.77
        },
        {
            rank: 59,
            country: "Guatemala",
            meal: 373.52,
            beer: 23.77,
            wine: 81.49,
            apartment: 5181.57,
            coffee: 25.52
        },
        {
            rank: 60,
            country: "Japan",
            meal: 363.2,
            beer: "29.jun",
            wine: 72.64,
            apartment: 6487.68,
            coffee: 31.91
        },
        {
            rank: 61,
            country: "Mauritius",
            meal: 357.87,
            beer: 23.86,
            wine: 113.32,
            apartment: 4390.94,
            coffee: 24.17
        },
        {
            rank: 62,
            country: "Kazakhstan",
            meal: 344.06,
            beer: 13.76,
            wine: 80.28,
            apartment: 6006.22,
            coffee: 21.22
        },
        {
            rank: 63,
            country: "Serbia",
            meal: 342.84,
            beer: "22.apr",
            wine: 68.57,
            apartment: 5656.88,
            coffee: "19.aug"
        },
        {
            rank: 64,
            country: "South Africa",
            meal: 341.4,
            beer: 19.92,
            wine: 45.52,
            apartment: 4336.59,
            coffee: 18.14
        },
        {
            rank: 65,
            country: "Taiwan",
            meal: 335.36,
            beer: "20.des",
            wine: 134.14,
            apartment: 4594.83,
            coffee: 30.52
        },
        {
            rank: 66,
            country: "Azerbaijan",
            meal: 314.36,
            beer: "des.57",
            wine: 62.87,
            apartment: 3544.12,
            coffee: 31.2
        },
        {
            rank: 67,
            country: "Russia",
            meal: 310.05,
            beer: 16.61,
            wine: 55.37,
            apartment: 3525.65,
            coffee: 17.8
        },
        {
            rank: 68,
            country: "Brazil",
            meal: 304.35,
            beer: 19.57,
            wine: 86.96,
            apartment: 3379.86,
            coffee: "18.apr"
        },
        {
            rank: 69,
            country: "Oman",
            meal: 298.48,
            beer: 111.06,
            wine: 194.36,
            apartment: 6030.57,
            coffee: 48.71
        },
        {
            rank: 70,
            country: "China",
            meal: 293.88,
            beer: "okt.29",
            wine: 117.55,
            apartment: 5363.9,
            coffee: 36.68
        },
        {
            rank: 71,
            country: "Kenya",
            meal: 291.63,
            beer: 18.23,
            wine: 87.49,
            apartment: 2237.28,
            coffee: 19.64
        },
        {
            rank: 72,
            country: "Ukraine",
            meal: 289.49,
            beer: "nov.58",
            wine: 49.21,
            apartment: 3819.51,
            coffee: 13.6
        },
        {
            rank: 73,
            country: "Bosnia And Herzegovina",
            meal: 281.74,
            beer: 17.61,
            wine: 58.7,
            apartment: 2461.58,
            coffee: 13.87
        },
        {
            rank: 74,
            country: "Palestine",
            meal: 279.45,
            beer: 29.34,
            wine: 125.75,
            apartment: 3221.07,
            coffee: "25.jan"
        },
        {
            rank: 75,
            country: "Argentina",
            meal: 267.21,
            beer: 20.31,
            wine: 32.06,
            apartment: 3014,
            coffee: 16.62
        },
        {
            rank: 76,
            country: "Iran",
            meal: 256.52,
            beer: "-",
            wine: "-",
            apartment: 3809.48,
            coffee: 13.46
        },
        {
            rank: 77,
            country: "Peru",
            meal: 245.61,
            beer: "23.des",
            wine: 86.69,
            apartment: 4179.59,
            coffee: 27.51
        },
        {
            rank: 78,
            country: "Colombia",
            meal: 241.46,
            beer: "12.jul",
            wine: 93.9,
            apartment: 3240.54,
            coffee: 15.2
        },
        {
            rank: 79,
            country: "Bolivia",
            meal: 239.8,
            beer: 18.57,
            wine: 62.98,
            apartment: 3198.73,
            coffee: "25.okt"
        },
        {
            rank: 80,
            country: "Thailand",
            meal: 239.37,
            beer: 20.95,
            wine: 179.53,
            apartment: 4177.77,
            coffee: 19.77
        },
        {
            rank: 81,
            country: "Uzbekistan",
            meal: 235.38,
            beer: "okt.69",
            wine: 42.75,
            apartment: 5178.72,
            coffee: 16.94
        },
        {
            rank: 82,
            country: "Iraq",
            meal: 234.95,
            beer: 21.36,
            wine: 122.46,
            apartment: 3816.92,
            coffee: 24.23
        },
        {
            rank: 83,
            country: "Kosovo (Disputed Territory)",
            meal: 229.74,
            beer: 20.68,
            wine: 45.95,
            apartment: 3388.13,
            coffee: "des.30"
        },
        {
            rank: 84,
            country: "Philippines",
            meal: 226.24,
            beer: 13.2,
            wine: 75.41,
            apartment: 3471.65,
            coffee: 25.54
        },
        {
            rank: 85,
            country: "North Macedonia",
            meal: 223.58,
            beer: 18.63,
            wine: 46.58,
            apartment: 2416.58,
            coffee: 15.39
        },
        {
            rank: 86,
            country: "Vietnam",
            meal: 220.79,
            beer: "11.apr",
            wine: 103.08,
            apartment: 3856.52,
            coffee: 19.61
        },
        {
            rank: 87,
            country: "Morocco",
            meal: 212.03,
            beer: 26.3,
            wine: 73.63,
            apartment: 3284.55,
            coffee: 16.62
        },
        {
            rank: 88,
            country: "Syria",
            meal: 202.55,
            beer: 16.57,
            wine: 53.44,
            apartment: 1721.04,
            coffee: "sep.63"
        },
        {
            rank: 89,
            country: "Nepal",
            meal: 201.38,
            beer: 24.17,
            wine: 64.44,
            apartment: 1252.59,
            coffee: 15.43
        },
        {
            rank: 90,
            country: "Turkey",
            meal: 198.33,
            beer: 19.83,
            wine: 79.33,
            apartment: 3830.01,
            coffee: "19.okt"
        },
        {
            rank: 91,
            country: "Algeria",
            meal: 194.82,
            beer: 15.59,
            wine: 74.03,
            apartment: 1794.81,
            coffee: "jun.62"
        },
        {
            rank: 92,
            country: "Malaysia",
            meal: 182.66,
            beer: 34.25,
            wine: 159.82,
            apartment: 3793.7,
            coffee: 26.51
        },
        {
            rank: 93,
            country: "Indonesia",
            meal: 174.03,
            beer: 27.84,
            wine: 208.83,
            apartment: 3231.29,
            coffee: 19.45
        },
        {
            rank: 94,
            country: "Egypt",
            meal: 172.95,
            beer: 17.29,
            wine: 77.83,
            apartment: 1585.34,
            coffee: 14.74
        },
        {
            rank: 95,
            country: "Tunisia",
            meal: 170.67,
            beer: 13.65,
            wine: 51.2,
            apartment: 2062.46,
            coffee: "jul.89"
        },
        {
            rank: 96,
            country: "Sri Lanka",
            meal: 165.24,
            beer: 16.52,
            wine: 99.14,
            apartment: 2180.14,
            coffee: 19.97
        },
        {
            rank: 97,
            country: "India",
            meal: 128.85,
            beer: 20.62,
            wine: 96.64,
            apartment: 2001.66,
            coffee: 18.59
        },
        {
            rank: 98,
            country: "Pakistan",
            meal: 116.93,
            beer: "-",
            wine: "-",
            apartment: 1071.43,
            coffee: 14.85
        },
        {
            rank: 99,
            country: "Bangladesh",
            meal: 97.42,
            beer: "-",
            wine: "-",
            apartment: 1045.52,
            coffee: "19.feb"
        }
    ],
    countries: [
        {
            name: "Afghanistan",
            continent: "Asia",
            capital: "Kabul",
            population: 38928346,
            area: 652230,
        },
        {
            name: "Albania",
            continent: "Europe",
            capital: "Tirana",
            population: 2877797,
            area: 28748,
        },
        {
            name: "Algeria",
            continent: "Africa",
            capital: "Algiers",
            population: 43851044,
            area: 2381741,
        },
        {
            name: "Andorra",
            continent: "Europe",
            capital: "Andorra la Vella",
            population: 77265,
            area: 468,
        },
        {
            name: "Angola",
            continent: "Africa",
            capital: "Luanda",
            population: 32866272,
            area: 1246700,
        },
        {
            name: "Antigua and Barbuda",
            continent: "North America",
            capital: "St. John's",
            population: 97928,
            area: 442,
        },
        {
            name: "Argentina",
            continent: "South America",
            capital: "Buenos Aires",
            population: 45195777,
            area: 2780400,
        },
        {
            name: "Armenia",
            continent: "Asia",
            capital: "Yerevan",
            population: 2963243,
            area: 29743,
        },
        {
            name: "Australia",
            continent: "Australia",
            capital: "Canberra",
            population: 25499884,
            area: 7692024,
        },
        {
            name: "Austria",
            continent: "Europe",
            capital: "Vienna",
            population: 9006398,
            area: 83871,
        },
        {
            name: "Azerbaijan",
            continent: "Asia",
            capital: "Baku",
            population: 10139177,
            area: 86600,
        },
        {
            name: "Bahamas",
            continent: "North America",
            capital: "Nassau",
            population: 393244,
            area: 13940,
        },
        {
            name: "Bahrain",
            continent: "Asia",
            capital: "Manama",
            population: 1701575,
            area: 760,
        },
        {
            name: "Bangladesh",
            continent: "Asia",
            capital: "Dhaka",
            population: 164689383,
            area: 147570,
        },
        {
            name: "Barbados",
            continent: "North America",
            capital: "Bridgetown",
            population: 287375,
            area: 431,
        },
        {
            name: "Belarus",
            continent: "Europe",
            capital: "Minsk",
            population: 9449323,
            area: 207600,
        },
        {
            name: "Belgium",
            continent: "Europe",
            capital: "Brussels",
            population: 11589623,
            area: 30528,
        },
        {
            name: "Belize",
            continent: "North America",
            capital: "Belmopan",
            population: 397628,
            area: 22966,
        },
        {
            name: "Benin",
            continent: "Africa",
            capital: "Porto-Novo",
            population: 12123198,
            area: 112622,
        },
        {
            name: "Bhutan",
            continent: "Asia",
            capital: "Thimphu",
            population: 771608,
            area: 38394,
        },
        {
            name: "Bolivia",
            continent: "South America",
            capital: "La Paz",
            population: 11673021,
            area: 1098581,
        },
        {
            name: "Bosnia and Herzegovina",
            continent: "Europe",
            capital: "Sarajevo",
            population: 3280815,
            area: 51197,
        },
        {
            name: "Botswana",
            continent: "Africa",
            capital: "Gaborone",
            population: 2351627,
            area: 581730,
        },
        {
            name: "Brazil",
            continent: "South America",
            capital: "Brasília",
            population: 212559417,
            area: 8515767,
        },
        {
            name: "Brunei",
            continent: "Asia",
            capital: "Bandar Seri Begawan",
            population: 437479,
            area: 5765,
        },
        {
            name: "Bulgaria",
            continent: "Europe",
            capital: "Sofia",
            population: 6948445,
            area: 110879,
        },
        {
            name: "Burkina Faso",
            continent: "Africa",
            capital: "Ouagadougou",
            population: 20903278,
            area: 274200,
        },
        {
            name: "Burundi",
            continent: "Africa",
            capital: "Bujumbura",
            population: 11890784,
            area: 27834,
        },
        {
            name: "Cabo Verde",
            continent: "Africa",
            capital: "Praia",
            population: 555987,
            area: 4033,
        },
        {
            name: "Cambodia",
            continent: "Asia",
            capital: "Phnom Penh",
            population: 16718971,
            area: 181035,
        },
        {
            name: "Cameroon",
            continent: "Africa",
            capital: "Yaoundé",
            population: 26545864,
            area: 475442,
        },
        {
            name: "Canada",
            continent: "North America",
            capital: "Ottawa",
            population: 37742154,
            area: 9984670,
        },
        {
            name: "Central African Republic",
            continent: "Africa",
            capital: "Bangui",
            population: 4829767,
            area: 622984,
        },
        {
            name: "Chad",
            continent: "Africa",
            capital: "N'Djamena",
            population: 16425859,
            area: 1284000,
        },
        {
            name: "Chile",
            continent: "South America",
            capital: "Santiago",
            population: 19116201,
            area: 756102,
        },
        {
            name: "China",
            continent: "Asia",
            capital: "Beijing",
            population: 1444216107,
            area: 9596961,
        },
        {
            name: "Colombia",
            continent: "South America",
            capital: "Bogotá",
            population: 50882891,
            area: 1141748,
        },
        {
            name: "Comoros",
            continent: "Africa",
            capital: "Moroni",
            population: 869601,
            area: 1862,
        },
        {
            name: "Congo (Congo-Brazzaville)",
            continent: "Africa",
            capital: "Brazzaville",
            population: 5518087,
            area: 342000,
        },
        {
            name: "Costa Rica",
            continent: "North America",
            capital: "San José",
            population: 5094118,
            area: 51100,
        },
        {
            name: "Croatia",
            continent: "Europe",
            capital: "Zagreb",
            population: 4105267,
            area: 56594,
        },
        {
            name: "Cuba",
            continent: "North America",
            capital: "Havana",
            population: 11326616,
            area: 110861,
        },
        {
            name: "Cyprus",
            continent: "Asia",
            capital: "Nicosia",
            population: 1207359,
            area: 5896,
        },
        {
            name: "Czechia (Czech Republic)",
            continent: "Europe",
            capital: "Prague",
            population: 10708981,
            area: 78865,
        },
        {
            name: "Democratic Republic of the Congo (Congo-Kinshasa)",
            continent: "Africa",
            capital: "Kinshasa",
            population: 85026000,
            area: 2344858,
        },
        {
            name: "Denmark",
            continent: "Europe",
            capital: "Copenhagen",
            population: 5792202,
            area: 43094,
        },
        {
            name: "Djibouti",
            continent: "Africa",
            capital: "Djibouti",
            population: 988000,
            area: 23000,
        },
        {
            name: "Dominica",
            continent: "North America",
            capital: "Roseau",
            population: 71986,
            area: 751,
        },
        {
            name: "Dominican Republic",
            continent: "North America",
            capital: "Santo Domingo",
            population: 10847910,
            area: 48671,
        },
        {
            name: "East Timor (Timor-Leste)",
            continent: "Asia",
            capital: "Dili",
            population: 1318445,
            area: 14874,
        },
        {
            name: "Ecuador",
            continent: "South America",
            capital: "Quito",
            population: 17643054,
            area: 276841,
        },
        {
            name: "Egypt",
            continent: "Africa",
            capital: "Cairo",
            population: 102334404,
            area: 1002450,
        },
        {
            name: "El Salvador",
            continent: "North America",
            capital: "San Salvador",
            population: 6486205,
            area: 21041,
        },
        {
            name: "Equatorial Guinea",
            continent: "Africa",
            capital: "Malabo",
            population: 1402985,
            area: 28051,
        },
        {
            name: "Eritrea",
            continent: "Africa",
            capital: "Asmara",
            population: 3546421,
            area: 117600,
        },
        {
            name: "Estonia",
            continent: "Europe",
            capital: "Tallinn",
            population: 1326535,
            area: 45227,
        },
        {
            name: "Eswatini (fmr. Swaziland)",
            continent: "Africa",
            capital: "Mbabane",
            population: 1160164,
            area: 17364,
        },
        {
            name: "Ethiopia",
            continent: "Africa",
            capital: "Addis Ababa",
            population: 114963588,
            area: 1104300,
        },
        {
            name: "Fiji",
            continent: "Oceania",
            capital: "Suva",
            population: 896445,
            area: 18274,
        },
        {
            name: "Finland",
            continent: "Europe",
            capital: "Helsinki",
            population: 5540720,
            area: 338424,
        },
        {
            name: "France",
            continent: "Europe",
            capital: "Paris",
            population: 65273511,
            area: 551695,
        },
        {
            name: "Gabon",
            continent: "Africa",
            capital: "Libreville",
            population: 2225734,
            area: 267667,
        },
        {
            name: "Gambia",
            continent: "Africa",
            capital: "Banjul",
            population: 2416668,
            area: 11295,
        },
        {
            name: "Georgia",
            continent: "Asia",
            capital: "Tbilisi",
            population: 3989167,
            area: 69700,
        },
        {
            name: "Germany",
            continent: "Europe",
            capital: "Berlin",
            population: 83783942,
            area: 357022,
        },
        {
            name: "Ghana",
            continent: "Africa",
            capital: "Accra",
            population: 31072940,
            area: 238533,
        },
        {
            name: "Greece",
            continent: "Europe",
            capital: "Athens",
            population: 10423054,
            area: 131957,
        },
        {
            name: "Grenada",
            continent: "North America",
            capital: "St. George's",
            population: 112523,
            area: 344,
        },
        {
            name: "Guatemala",
            continent: "North America",
            capital: "Guatemala City",
            population: 17915568,
            area: 108889,
        },
        {
            name: "Guinea",
            continent: "Africa",
            capital: "Conakry",
            population: 13132795,
            area: 245857,
        },
        {
            name: "Guinea-Bissau",
            continent: "Africa",
            capital: "Bissau",
            population: 1967998,
            area: 36125,
        },
        {
            name: "Guyana",
            continent: "South America",
            capital: "Georgetown",
            population: 786552,
            area: 214969,
        },
        {
            name: "Haiti",
            continent: "North America",
            capital: "Port-au-Prince",
            population: 11402533,
            area: 27750,
        },
        {
            name: "Holy See",
            continent: "Europe",
            capital: "Vatican City",
            population: 801,
            area: 0.44,
        },
        {
            name: "Honduras",
            continent: "North America",
            capital: "Tegucigalpa",
            population: 9904607,
            area: 112492,
        },
        {
            name: "Hungary",
            continent: "Europe",
            capital: "Budapest",
            population: 9660351,
            area: 93030,
        },
        {
            name: "Iceland",
            continent: "Europe",
            capital: "Reykjavik",
            population: 341243,
            area: 103000,
        },
        {
            name: "India",
            continent: "Asia",
            capital: "New Delhi",
            population: 1380004385,
            area: 3287263,
        },
        {
            name: "Indonesia",
            continent: "Asia",
            capital: "Jakarta",
            population: 273523615,
            area: 1904569,
        },
        {
            name: "Iran",
            continent: "Asia",
            capital: "Tehran",
            population: 83992949,
            area: 1648195,
        },
        {
            name: "Iraq",
            continent: "Asia",
            capital: "Baghdad",
            population: 40222493,
            area: 438317,
        },
        {
            name: "Ireland",
            continent: "Europe",
            capital: "Dublin",
            population: 4937786,
            area: 70273,
        },
        {
            name: "Israel",
            continent: "Asia",
            capital: "Jerusalem",
            population: 8655535,
            area: 20770,
        },
        {
            name: "Italy",
            continent: "Europe",
            capital: "Rome",
            population: 60461826,
            area: 301340,
        },
        {
            name: "Jamaica",
            continent: "North America",
            capital: "Kingston",
            population: 2961161,
            area: 10991,
        },
        {
            name: "Japan",
            continent: "Asia",
            capital: "Tokyo",
            population: 126476461,
            area: 377975,
        },
        {
            name: "Jordan",
            continent: "Asia",
            capital: "Amman",
            population: 10203134,
            area: 89342,
        },
        {
            name: "Kazakhstan",
            continent: "Asia",
            capital: "Nur-Sultan",
            population: 18776707,
            area: 2724900,
        },
        {
            name: "Kenya",
            continent: "Africa",
            capital: "Nairobi",
            population: 53771296,
            area: 580367,
        },
        {
            name: "Kiribati",
            continent: "Oceania",
            capital: "Tarawa",
            population: 119449,
            area: 811,
        },
        {
            name: "Kuwait",
            continent: "Asia",
            capital: "Kuwait City",
            population: 4270571,
            area: 17818,
        },
        {
            name: "Kyrgyzstan",
            continent: "Asia",
            capital: "Bishkek",
            population: 6524195,
            area: 199951,
        },
        {
            name: "Laos",
            continent: "Asia",
            capital: "Vientiane",
            population: 7275560,
            area: 236800,
        },
        {
            name: "Latvia",
            continent: "Europe",
            capital: "Riga",
            population: 1886198,
            area: 64559,
        },
        {
            name: "Lebanon",
            continent: "Asia",
            capital: "Beirut",
            population: 6825442,
            area: 10452,
        },
        {
            name: "Lesotho",
            continent: "Africa",
            capital: "Maseru",
            population: 2142249,
            area: 30355,
        },
        {
            name: "Liberia",
            continent: "Africa",
            capital: "Monrovia",
            population: 5057681,
            area: 111369,
        },
        {
            name: "Libya",
            continent: "Africa",
            capital: "Tripoli",
            population: 6871287,
            area: 1759540,
        },
        {
            name: "Liechtenstein",
            continent: "Europe",
            capital: "Vaduz",
            population: 38128,
            area: 160,
        },
        {
            name: "Lithuania",
            continent: "Europe",
            capital: "Vilnius",
            population: 2722289,
            area: 65300,
        },
        {
            name: "Luxembourg",
            continent: "Europe",
            capital: "Luxembourg City",
            population: 625978,
            area: 2586,
        },
        {
            name: "Madagascar",
            continent: "Africa",
            capital: "Antananarivo",
            population: 27691019,
            area: 587041,
        },
        {
            name: "Malawi",
            continent: "Africa",
            capital: "Lilongwe",
            population: 19129952,
            area: 118484,
        },
        {
            name: "Malaysia",
            continent: "Asia",
            capital: "Kuala Lumpur",
            population: 32365999,
            area: 330803,
        },
        {
            name: "Maldives",
            continent: "Asia",
            capital: "Malé",
            population: 521167,
            area: 298,
        },
        {
            name: "Mali",
            continent: "Africa",
            capital: "Bamako",
            population: 20250833,
            area: 1240192,
        },
        {
            name: "Malta",
            continent: "Europe",
            capital: "Valletta",
            population: 441543,
            area: 316,
        },
        {
            name: "Marshall Islands",
            continent: "Oceania",
            capital: "Majuro",
            population: 59190,
            area: 181,
        },
        {
            name: "Mauritania",
            continent: "Africa",
            capital: "Nouakchott",
            population: 4649658,
            area: 1030700,
        },
        {
            name: "Mauritius",
            continent: "Africa",
            capital: "Port Louis",
            population: 1271768,
            area: 2040,
        },
        {
            name: "Mexico",
            continent: "North America",
            capital: "Mexico City",
            population: 128932753,
            area: 1964375,
        },
        {
            name: "Micronesia",
            continent: "Oceania",
            capital: "Palikir",
            population: 115023,
            area: 702,
        },
        {
            name: "Moldova",
            continent: "Europe",
            capital: "Chisinau",
            population: 4033963,
            area: 33846,
        },
        {
            name: "Monaco",
            continent: "Europe",
            capital: "Monaco",
            population: 39242,
            area: 2,
        },
        {
            name: "Mongolia",
            continent: "Asia",
            capital: "Ulaanbaatar",
            population: 3278290,
            area: 1564116,
        },
        {
            name: "Montenegro",
            continent: "Europe",
            capital: "Podgorica",
            population: 628066,
            area: 13812,
        },
        {
            name: "Morocco",
            continent: "Africa",
            capital: "Rabat",
            population: 36910560,
            area: 446550,
        },
        {
            name: "Mozambique",
            continent: "Africa",
            capital: "Maputo",
            population: 31255435,
            area: 801590,
        },
        {
            name: "Myanmar (Burma)",
            continent: "Asia",
            capital: "Naypyidaw",
            population: 54409800,
            area: 676578,
        },
        {
            name: "Namibia",
            continent: "Africa",
            capital: "Windhoek",
            population: 2540905,
            area: 824292,
        },
        {
            name: "Nauru",
            continent: "Oceania",
            capital: "Yaren",
            population: 10824,
            area: 21,
        },
        {
            name: "Nepal",
            continent: "Asia",
            capital: "Kathmandu",
            population: 29136808,
            area: 147516,
        },
        {
            name: "Netherlands",
            continent: "Europe",
            capital: "Amsterdam",
            population: 17134872,
            area: 41543,
        },
        {
            name: "New Zealand",
            continent: "Oceania",
            capital: "Wellington",
            population: 4822233,
            area: 270467,
        },
        {
            name: "Nicaragua",
            continent: "North America",
            capital: "Managua",
            population: 6624554,
            area: 130375,
        },
        {
            name: "Niger",
            continent: "Africa",
            capital: "Niamey",
            population: 24206636,
            area: 1186408,
        },
        {
            name: "Nigeria",
            continent: "Africa",
            capital: "Abuja",
            population: 206139587,
            area: 923768,
        },
        {
            name: "North Korea (DPRK)",
            continent: "Asia",
            capital: "Pyongyang",
            population: 25778816,
            area: 120538,
        },
        {
            name: "North Macedonia",
            continent: "Europe",
            capital: "Skopje",
            population: 2083374,
            area: 25713,
        },
        {
            name: "Norway",
            continent: "Europe",
            capital: "Oslo",
            population: 5421241,
            area: 323802,
        },
        {
            name: "Oman",
            continent: "Asia",
            capital: "Muscat",
            population: 5106626,
            area: 309500,
        },
        {
            name: "Pakistan",
            continent: "Asia",
            capital: "Islamabad",
            population: 220892340,
            area: 881913,
        },
        {
            name: "Palau",
            continent: "Oceania",
            capital: "Ngerulmud",
            population: 18094,
            area: 459,
        },
        {
            name: "Palestine State",
            continent: "Asia",
            capital: "East Jerusalem",
            population: 5101414,
            area: 6020,
        },
        {
            name: "Panama",
            continent: "North America",
            capital: "Panama City",
            population: 4314767,
            area: 75420,
        },
        {
            name: "Papua New Guinea",
            continent: "Oceania",
            capital: "Port Moresby",
            population: 8947024,
            area: 462840,
        },
        {
            name: "Paraguay",
            continent: "South America",
            capital: "Asunción",
            population: 7132530,
            area: 406752,
        },
        {
            name: "Peru",
            continent: "South America",
            capital: "Lima",
            population: 32971854,
            area: 1285216,
        },
        {
            name: "Philippines",
            continent: "Asia",
            capital: "Manila",
            population: 113993580,
            area: 342353,
        },
        {
            name: "Poland",
            continent: "Europe",
            capital: "Warsaw",
            population: 37846611,
            area: 312696,
        },
        {
            name: "Portugal",
            continent: "Europe",
            capital: "Lisbon",
            population: 10196709,
            area: 92090,
        },
        {
            name: "Qatar",
            continent: "Asia",
            capital: "Doha",
            population: 2881053,
            area: 11586,
        },
        {
            name: "Romania",
            continent: "Europe",
            capital: "Bucharest",
            population: 19237691,
            area: 238397,
        },
        {
            name: "Russia",
            continent: "Europe/Asia",
            capital: "Moscow",
            population: 145912025,
            area: 17125242,
        },
        {
            name: "Rwanda",
            continent: "Africa",
            capital: "Kigali",
            population: 12952218,
            area: 26338,
        },
        {
            name: "Saint Kitts and Nevis",
            continent: "North America",
            capital: "Basseterre",
            population: 53199,
            area: 261,
        },
        {
            name: "Saint Lucia",
            continent: "North America",
            capital: "Castries",
            population: 183627,
            area: 616,
        },
        {
            name: "Saint Vincent and the Grenadines",
            continent: "North America",
            capital: "Kingstown",
            population: 110940,
            area: 389,
        },
        {
            name: "Samoa",
            continent: "Oceania",
            capital: "Apia",
            population: 198414,
            area: 2831,
        },
        {
            name: "San Marino",
            continent: "Europe",
            capital: "San Marino",
            population: 33938,
            area: 61,
        },
        {
            name: "Sao Tome and Principe",
            continent: "Africa",
            capital: "São Tomé",
            population: 219159,
            area: 964,
        },
        {
            name: "Saudi Arabia",
            continent: "Asia",
            capital: "Riyadh",
            population: 34813871,
            area: 2149690,
        },
        {
            name: "Senegal",
            continent: "Africa",
            capital: "Dakar",
            population: 16743927,
            area: 196722,
        },
        {
            name: "Serbia",
            continent: "Europe",
            capital: "Belgrade",
            population: 8737371,
            area: 77474,
        },
        {
            name: "Seychelles",
            continent: "Africa",
            capital: "Victoria",
            population: 98347,
            area: 459,
        },
        {
            name: "Sierra Leone",
            continent: "Africa",
            capital: "Freetown",
            population: 7976983,
            area: 71740,
        },
        {
            name: "Singapore",
            continent: "Asia",
            capital: "Singapore",
            population: 5850342,
            area: 719,
        },
        {
            name: "Slovakia",
            continent: "Europe",
            capital: "Bratislava",
            population: 5460109,
            area: 49035,
        },
        {
            name: "Slovenia",
            continent: "Europe",
            capital: "Ljubljana",
            population: 2078938,
            area: 20273,
        },
        {
            name: "Solomon Islands",
            continent: "Oceania",
            capital: "Honiara",
            population: 686878,
            area: 28896,
        },
        {
            name: "Somalia",
            continent: "Africa",
            capital: "Mogadishu",
            population: 15893222,
            area: 637657,
        },
        {
            name: "South Africa",
            continent: "Africa",
            capital: "Pretoria, Bloemfontein, Cape Town",
            population: 59308690,
            area: 1221037,
        },
        {
            name: "South Korea (Republic of Korea)",
            continent: "Asia",
            capital: "Seoul",
            population: 51269185,
            area: 100210,
        },
        {
            name: "South Sudan",
            continent: "Africa",
            capital: "Juba",
            population: 11193729,
            area: 619745,
        },
        {
            name: "Spain",
            continent: "Europe",
            capital: "Madrid",
            population: 46754778,
            area: 505990,
        },
        {
            name: "Sri Lanka",
            continent: "Asia",
            capital: "Colombo",
            population: 21413249,
            area: 65610,
        },
        {
            name: "Sudan",
            continent: "Africa",
            capital: "Khartoum",
            population: 43849260,
            area: 1861484,
        },
        {
            name: "Suriname",
            continent: "South America",
            capital: "Paramaribo",
            population: 586632,
            area: 163821,
        },
        {
            name: "Sweden",
            continent: "Europe",
            capital: "Stockholm",
            population: 10099265,
            area: 450295,
        },
        {
            name: "Switzerland",
            continent: "Europe",
            capital: "Bern",
            population: 8654622,
            area: 41284,
        },
        {
            name: "Syria",
            continent: "Asia",
            capital: "Damascus",
            population: 17500657,
            area: 185180,
        },
        {
            name: "Tajikistan",
            continent: "Asia",
            capital: "Dushanbe",
            population: 9537645,
            area: 143100,
        },
        {
            name: "Tanzania",
            continent: "Africa",
            capital: "Dodoma",
            population: 59734218,
            area: 947303,
        },
        {
            name: "Thailand",
            continent: "Asia",
            capital: "Bangkok",
            population: 69799978,
            area: 513120,
        },
        {
            name: "Togo",
            continent: "Africa",
            capital: "Lome",
            population: 8278737,
            area: 56785,
        },
        {
            name: "Tonga",
            continent: "Oceania",
            capital: "Nuku'alofa",
            population: 105695,
            area: 747,
        },
        {
            name: "Trinidad and Tobago",
            continent: "North America",
            capital: "Port of Spain",
            population: 1394973,
            area: 5130,
        },
        {
            name: "Tunisia",
            continent: "Africa",
            capital: "Tunis",
            population: 11818619,
            area: 163610,
        },
        {
            name: "Turkey",
            continent: "Asia/Europe",
            capital: "Ankara",
            population: 84339067,
            area: 783562,
        },
        {
            name: "Turkmenistan",
            continent: "Asia",
            capital: "Ashgabat",
            population: 6031187,
            area: 488100,
        },
        {
            name: "Tuvalu",
            continent: "Oceania",
            capital: "Funafuti",
            population: 11704,
            area: 26,
        },
        {
            name: "Uganda",
            continent: "Africa",
            capital: "Kampala",
            population: 45741007,
            area: 241038,
        },
        {
            name: "Ukraine",
            continent: "Europe",
            capital: "Kyiv",
            population: 44385155,
            area: 603500,
        },
        {
            name: "United Arab Emirates",
            continent: "Asia",
            capital: "Abu Dhabi",
            population: 9890402,
            area: 83600,
        },
        {
            name: "United Kingdom",
            continent: "Europe",
            capital: "London",
            population: 67886011,
            area: 242495,
        },
        {
            name: "United States of America",
            continent: "North America",
            capital: "Washington, D.C.",
            population: 331002651,
            area: 9372610,
        },
        {
            name: "Uruguay",
            continent: "South America",
            capital: "Montevideo",
            population: 3473730,
            area: 181034,
        },
        {
            name: "Uzbekistan",
            continent: "Asia",
            capital: "Tashkent",
            population: 33469203,
            area: 448978,
        },
        {
            name: "Vanuatu",
            continent: "Oceania",
            capital: "Port Vila",
            population: 307145,
            area: 12189,
        },
        {
            name: "Venezuela",
            continent: "South America",
            capital: "Caracas",
            population: 28435943,
            area: 916445,
        },
        {
            name: "Vietnam",
            continent: "Asia",
            capital: "Hanoi",
            population: 97338579,
            area: 331212,
        },
        {
            name: "Yemen",
            continent: "Asia",
            capital: "Sanaa",
            population: 29825968,
            area: 527968,
        },
        {
            name: "Zambia",
            continent: "Africa",
            capital: "Lusaka",
            population: 18383955,
            area: 752612,
        },
        {
            name: "Zimbabwe",
            continent: "Africa",
            capital: "Harare",
            population: 14862927,
            area: 390757,
        },
    ]
};